terminate called after throwing an instance of 'std::out_of_range'
  what():  bitset::set: __position (which is 2147483647) >= _Nb (which is 200005)
